### ISSUE TITLE
Superuser permission

### ISSUE THREAD

**Issue by tommasobenatti** [etil2jz/etil-minecraft-flags#1]
Hi, I tried your flags with Graal EE with a non root account and I had this warning at startup
`Java HotSpot(TM) 64-Bit Server VM warning: -XX:ThreadPriorityPolicy=1 may require system level permission, e.g., being the root user. If the necessary permission is not possessed, changes to priority will be silently ignored.`

Can I ignore this or should I run the server with the root user?

**Comment by LewUwU** [comment]
A server should never run with root permissions, this is a big security risk.
