### ISSUE TITLE
Client Flags?

### ISSUE THREAD

**Issue by kaeltis** [etil2jz/etil-minecraft-flags#3]
Hi,

first of all, thanks for your work on this, it's great to have an up to date source for these kind of JVM tweaks.

Would these flags also be helpful for a client or are they only geared towards servers and would hinder client performance? If so it would be great to have two sections like "Server Flags" and "Client Flags" to be able to optimize the clients as well, especially the heavily modded ones.

**Comment by etil2jz** [comment]
Hi,
These flags can work on both server and client with great performance. Otherwise since Java 17, Shenandoah outperforms G1, I may write a dedicated section for the Shenandoah GC once it's added in GraalVM!

**Comment by kaeltis** [comment]
Thanks!
