### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by lele92007** [etil2jz/etil-minecraft-flags#9]
1. minecraft 1.16.5 (with mods) and older only support up to java 8, do you have any specific recommendations for this version ?
2. do you have flags recommendations for clients ?
3. i remember reading something about "large pages" on aikar's site, did you take that into account when saying to avoid using more than 20 gigs ?

**Comment by etil2jz** [comment]
1. Minecraft 1.16.5 can actually support higher Java versions by adding `--add-exports=java.base/sun.security.util=ALL-UNNAMED --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming --add-opens=java.base/java.util.jar=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED` in Java flags.
2. The same flags should work fine with clients.
3. Large Pages is useful with Shenandoah GC, the 20GB maximum concerns G1 GC.

**Comment by lele92007** [comment]
thx

**Comment by lele92007** [comment]
![image](https://user-images.githubusercontent.com/77411734/190451389-a5d8741d-c663-4a02-8a6e-ca55f29e9af2.png)
i am dumb

**Comment by lele92007** [comment]
another question, i am using linux on a laptop with an i3 5th gen, and the packet manager installed the amd64 version of java, but the x64 adoptium worked fine.
is there a difference between the twos, and should i prefer one over the other ?

**Comment by etil2jz** [comment]
amd64 **is** x64
